{"uri":"file:///Users/vega/Code/huli/manager-web/src/vendor/aws/aws-sdk-php/src/Aws/DynamoDb/Exception/InternalFailureException.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Aws\\DynamoDb\\Exception","location":[16,0,16,33]},{"kind":1,"name":"Aws\\DynamoDb\\Exception\\InternalFailureException","location":[21,0,21,59],"associated":[{"kind":1,"name":"Aws\\DynamoDb\\Exception\\DynamoDbException"}],"description":"The server encountered an internal error trying to fulfill the request."}]}}