{"uri":"file:///Users/vega/Code/huli/manager-web/src/vendor/phpunit/phpunit/src/Framework/ExceptionWrapper.php","root":{"kind":0,"name":"","children":[{"kind":1,"name":"PHPUnit_Framework_ExceptionWrapper","location":[19,0,88,1],"associated":[{"kind":1,"name":"PHPUnit_Framework_Exception"}],"description":"Wraps Exceptions thrown by code under test.\n\nRe-instantiates Exceptions thrown by user-space code to retain their original\nclass names, properties, and stack traces (but without arguments).\n\nUnlike PHPUnit_Framework_Exception, the complete stack of previous Exceptions\nis processed.","children":[{"kind":16,"name":"$className","modifiers":2,"location":[24,14,24,24],"scope":"PHPUnit_Framework_ExceptionWrapper","type":"string"},{"kind":16,"name":"$previous","modifiers":2,"location":[29,14,29,23],"scope":"PHPUnit_Framework_ExceptionWrapper","type":"PHPUnit_Framework_ExceptionWrapper|null"},{"kind":32,"name":"__construct","modifiers":1,"location":[34,4,53,5],"scope":"PHPUnit_Framework_ExceptionWrapper","children":[{"kind":128,"name":"$e","location":[34,32,34,34],"scope":"__construct","type":"Throwable|Exception"}]},{"kind":32,"name":"getClassName","modifiers":1,"location":[58,4,61,5],"scope":"PHPUnit_Framework_ExceptionWrapper","type":"string"},{"kind":32,"name":"getPreviousWrapped","modifiers":1,"location":[66,4,69,5],"scope":"PHPUnit_Framework_ExceptionWrapper","type":"PHPUnit_Framework_ExceptionWrapper"},{"kind":32,"name":"__toString","modifiers":1,"location":[74,4,87,5],"scope":"PHPUnit_Framework_ExceptionWrapper","type":"string"}]}]}}